# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/aram/Downloads/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/aram/Desktop/U5_MVAE/UE5_MVAE/MVAE.uproject

TARGETS = \
	MVAE-Linux-DebugGame  \
	MVAE-Linux-Shipping  \
	MVAE \
	MVAEEditor-Linux-DebugGame  \
	MVAEEditor-Linux-Shipping  \
	MVAEEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MVAEEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MVAEEditor-Linux-Debug


MVAE-Linux-DebugGame:
	 $(PROJECTBUILD) MVAE Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MVAE-Linux-Shipping:
	 $(PROJECTBUILD) MVAE Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MVAE:
	 $(PROJECTBUILD) MVAE Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MVAEEditor-Linux-DebugGame:
	 $(PROJECTBUILD) MVAEEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MVAEEditor-Linux-Shipping:
	 $(PROJECTBUILD) MVAEEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MVAEEditor:
	 $(PROJECTBUILD) MVAEEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
